### ISSUE TITLE
Doesn't build with Boost 1.71 (Ubuntu Focal)

### ISSUE THREAD

**Issue by mikepurvis** [SICKAG/sick_safetyscanners#41]
Issue is here:

```
.../src/sick_safetyscanners/src/communication/AsyncTCPClient.cpp:51:91:   required from here
/usr/include/boost/asio/detail/io_object_impl.hpp:87:40: error: const class boost::reference_wrapper<boost::asio::io_context> has no member named get_executor
```

And the same thing in `AsyncUDPClient.cpp`.

Related: https://github.com/boostorg/asio/issues/227

**Comment by puck-fzi** [comment]
As I understand this change is backwards compatible to earlier boost versions. Tested on my local setup, works fine therefore to assure usage under ubuntu focal with  boost 1.71 it will be merged

**Comment by mikepurvis** [comment]
Great, thanks for the quick merges!

**Comment by JingD** [comment]
Having the same issue while bringing boost 1570 to 1720, can anyone let me know how this is fixed please? :-)

**Comment by puck-fzi** [comment]
It should be merged into the current master.

It is tested with 1.71 from @mikepurvis, I haven't checked 1.72, and only assured backwards compatibility. If there are more changes which need to be made, let me know.

**Comment by anauta2014** [comment]
I have code with
ip::tcp::acceptor acc_;
if(acc_.get_io_service().stopped())...
this works with boost 1.69
How can I change this code for boost 1.70+ ?

**Comment by puck-fzi** [comment]
Hi anuta, this is appears to not be relevant for this ROS package, is this an independent program of yours?
If so, please refer with your question to the documentation of boost or if that does not help to stackoverflow.
